# Generated by Django 4.0 on 2023-07-04 09:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Pill name')),
                ('description', models.CharField(blank=True, max_length=700, verbose_name='Pill description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pill', to='accounts.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Pill',
                'verbose_name_plural': 'Pills',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='UniversalPill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Pill name')),
                ('description', models.CharField(blank=True, max_length=700, verbose_name='Pill description')),
                ('application', models.CharField(blank=True, max_length=700, verbose_name='Pill application')),
                ('is_active', models.BooleanField(default=False, verbose_name='Pill is active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Universal Pill',
                'verbose_name_plural': 'Universal Pills',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='PillAlarm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=700, verbose_name='Alarm description')),
                ('is_active', models.BooleanField(default=False, verbose_name='Alarm is active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('periodic_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='django_celery_beat.periodictask', verbose_name='Periodic Task')),
                ('pill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='pills.pill', verbose_name='Pill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='accounts.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Pill alarm',
                'verbose_name_plural': 'Pill alarms',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='AlarmNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumed', models.BooleanField(default=True, verbose_name='Pill was consumed')),
                ('consumed_at', models.DateTimeField(verbose_name='Consumed at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pills.pillalarm', verbose_name='Alarm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Pill notification',
                'verbose_name_plural': 'Pill notifications',
                'ordering': ('created',),
            },
        ),
    ]
