# Generated by Django 4.0 on 2023-07-09 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('pills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pillalarm',
            name='periodic_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='django_celery_beat.periodictask', verbose_name='Periodic Task'),
        ),
    ]
